name:                funcy-compiler
version:             0.1.0.0
github:              "Abastro/funcy-compiler"
license:             BSD3
author:              "Abastro"
maintainer:          "abab9579@gmail.com"
copyright:           "2019 Abastro"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Abastro/funcy-compiler#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  funcy-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funcy-compiler

tests:
  funcy-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - funcy-compiler
